apiVersion: kubesphere.io/v1alpha1
kind: ExtensionVersion
metadata:
  creationTimestamp: null
  labels:
    kubesphere.io/category: computing
    kubesphere.io/extension-ref: kubeedge
  name: kubeedge-{{ .Values.kubeedge.version }}
spec:
  category: computing
  created: "2024-05-15T09:18:25Z"
  description:
    en: KubeEdge is built upon Kubernetes and extends native containerized application orchestration and device management to hosts at the Edge.
    zh: KubeEdge 是一个开源的系统，可将本机容器化应用编排和管理扩展到边缘端设备。
  displayName:
    en: KubeEdge Edge Computing Framework
    zh: KubeEdge 边缘计算框架
  docs: https://docs.kubesphere.com.cn/
  home: https://kubesphere.com.cn/
  icon: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxnIGNsaXAtcGF0aD0idXJsKCNjbGlwMF8xNjBfNDM4MikiPgo8cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTIxLjA1MjcgMjAuODMzM0MxNi4yMDgxIDIwLjgzMzMgMTIuMjgwOCAyNC43NjA2IDEyLjI4MDggMjkuNjA1MlY4Mi4yMzY4SDE4Ny43MTlWMjkuNjA1MkMxODcuNzE5IDI0Ljc2MDYgMTgzLjc5MiAyMC44MzMzIDE3OC45NDcgMjAuODMzM0gyMS4wNTI3WiIgZmlsbD0iIzU1QkM4QSIvPgo8cGF0aCBkPSJNMTg3LjcyIDk1LjM5NUgxMi4yODEyVjExMi45MzlINDkuNTYxMlYxMzEuNjEyQzQ5LjU2MTIgMTMxLjk4NCA0OS40NjY3IDEzMi4zNDkgNDkuMjg2OCAxMzIuNjc0TDQyLjkxOTMgMTQ0LjE3N0M0MS41MzY2IDE0My44MjcgNDAuMDg4NSAxNDMuNjQxIDM4LjU5NjkgMTQzLjY0MUMyOC45MDc3IDE0My42NDEgMjEuMDUzMSAxNTEuNDk1IDIxLjA1MzEgMTYxLjE4NEMyMS4wNTMxIDE3MC44NzQgMjguOTA3NyAxNzguNzI4IDM4LjU5NjkgMTc4LjcyOEM0OC4yODYxIDE3OC43MjggNTYuMTQwOCAxNzAuODc0IDU2LjE0MDggMTYxLjE4NEM1Ni4xNDA4IDE1Ny44NDYgNTUuMjA4NCAxNTQuNzI2IDUzLjU4OTkgMTUyLjA2OUw2MC43OTg1IDEzOS4wNDdDNjIuMDU4MiAxMzYuNzcyIDYyLjcxOSAxMzQuMjEzIDYyLjcxOSAxMzEuNjEyVjExMi45MzlIOTMuNDIxNVYxNTMuNjg4Qzg2Ljk5MiAxNTYuMjkgODIuNDU2NiAxNjIuNTk0IDgyLjQ1NjYgMTY5Ljk1NkM4Mi40NTY2IDE3OS42NDYgOTAuMzExMiAxODcuNSAxMDAgMTg3LjVDMTA5LjY5IDE4Ny41IDExNy41NDQgMTc5LjY0NiAxMTcuNTQ0IDE2OS45NTZDMTE3LjU0NCAxNjIuNTk0IDExMy4wMDkgMTU2LjI5IDEwNi41NzkgMTUzLjY4OFYxMTIuOTM5SDEzNy4yODJWMTMxLjYxMkMxMzcuMjgyIDEzNC4yMTMgMTM3Ljk0MyAxMzYuNzcyIDEzOS4yMDIgMTM5LjA0N0wxNDYuNDExIDE1Mi4wNjlDMTQ0Ljc5MiAxNTQuNzI2IDE0My44NiAxNTcuODQ2IDE0My44NiAxNjEuMTg0QzE0My44NiAxNzAuODc0IDE1MS43MTUgMTc4LjcyOCAxNjEuNDA0IDE3OC43MjhDMTcxLjA5MyAxNzguNzI4IDE3OC45NDggMTcwLjg3NCAxNzguOTQ4IDE2MS4xODRDMTc4Ljk0OCAxNTEuNDk1IDE3MS4wOTMgMTQzLjY0MSAxNjEuNDA0IDE0My42NDFDMTU5LjkxMiAxNDMuNjQxIDE1OC40NjQgMTQzLjgyNyAxNTcuMDgyIDE0NC4xNzdMMTUwLjcxNCAxMzIuNjc0QzE1MC41MzQgMTMyLjM0OSAxNTAuNDQgMTMxLjk4NCAxNTAuNDQgMTMxLjYxMlYxMTIuOTM5SDE4Ny43MlY5NS4zOTVaIiBmaWxsPSIjMzI0NTU4Ii8+CjxyZWN0IHg9IjEyLjI4MTIiIHk9Ijk1LjM5NSIgd2lkdGg9IjE3NS40MzkiIGhlaWdodD0iMTcuNTM1NiIgZmlsbD0iIzU1QkM4QSIvPgo8cGF0aCBkPSJNOTUuODQyNiAzOC4zNzdIMTIyLjE1OFY1NS45MjA4SDk1Ljg0MjZWMzguMzc3WiIgZmlsbD0iI0E4RERDMyIvPgo8cGF0aCBkPSJNMjkuODI1MSAzOC4zNzdIODIuNDU2N1Y1NS45MjA4SDI5LjgyNTFWMzguMzc3WiIgZmlsbD0id2hpdGUiLz4KPHJlY3Qgb3BhY2l0eT0iMC4yIiB4PSIxMi4yODEyIiB5PSI5NS4zOTUiIHdpZHRoPSI1OC40Nzk1IiBoZWlnaHQ9IjE3LjUzNTYiIGZpbGw9IndoaXRlIi8+CjxyZWN0IG9wYWNpdHk9IjAuNCIgeD0iNzAuNzYxNSIgeT0iOTUuMzk1IiB3aWR0aD0iNTguNDc5NSIgaGVpZ2h0PSIxNy41MzU2IiBmaWxsPSJ3aGl0ZSIvPgo8cmVjdCBvcGFjaXR5PSIwLjYiIHg9IjEyOS4yNDEiIHk9Ijk1LjM5NSIgd2lkdGg9IjU4LjQ3OTUiIGhlaWdodD0iMTcuNTM1NiIgZmlsbD0id2hpdGUiLz4KPC9nPgo8ZGVmcz4KPGNsaXBQYXRoIGlkPSJjbGlwMF8xNjBfNDM4MiI+CjxyZWN0IHdpZHRoPSIxNzUuNDM5IiBoZWlnaHQ9IjE2Ni42NjciIGZpbGw9IndoaXRlIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxMi4yODA4IDIwLjgzMzMpIi8+CjwvY2xpcFBhdGg+CjwvZGVmcz4KPC9zdmc+Cg==
  installationMode: HostOnly
  keywords:
    - Edge Computing
    - KubeEdge
  ksVersion: '>=4.0.0-0'
  kubeVersion: '>=1.19.0-0'
  namespace: kubeedge
  provider:
    en:
      email: kubesphere@yunify.com
      name: QingCloud Technologies
      url: https://kubesphere.co/
    zh:
      email: kubesphere@yunify.com
      name: 北京青云科技股份有限公司
      url: https://kubesphere.com.cn/
  version: '{{ .Values.kubeedge.version }}'
  chartURL: '{{ include "proxy-chart.repository" ( dict "name" "kubeedge" "version" .Values.kubeedge.version "Values" .Values "Release" .Release ) }}'
