global:
  imageRegistry: registry.cn-beijing.aliyuncs.com
  tag: v4.1.0-20240515-1
  imagePullSecrets: []

oci:
  repository: hub.kubesphere.com.cn/kse-extensions
  scheme: https
#  username: username
#  password: password
  registry:
    enabled: false
    image:
      registry: ""
      repository: "kubesphereio/registry"
      tag: 2.8.3
museum:
  enabled: false
  image:
    registry: ""
    repository: "kse/extensions-museum"
    tag: ""

devops:
  version: 1.1.0
dmp:
  version: 2.1.2
gatekeeper:
  version: 1.0.0
gateway:
  version: 1.0.0
kubeedge:
  version: 1.13.1
kubefed:
  version: 1.0.0
metrics_server:
  version: 0.7.0
network:
  version: 1.0.0
openpitrix:
  version: 2.0.0
opensearch:
  version: 2.11.1
servicemesh:
  version: 1.0.0
springcloud:
  version: 1.0.0
storage_utils:
  version: 1.0.0
tower:
  version: 1.0.0
vector:
  version: 1.0.0
whizard_alerting:
  version: 1.0.1
whizard_auditing:
  version: 1.0.1
whizard_events:
  version: 1.0.1
whizard_logging:
  version: 1.0.1
whizard_monitoring:
  version: 1.0.0
whizard_notification:
  version: 2.5.6
whizard_telemetry:
  version: 1.0.0
whizard_telemetry_ruler:
  version: 1.0.0
