apiVersion: kubesphere.io/v1alpha1
kind: InstallPlan
metadata:
  annotations:
    kubesphere.io/installation-mode: "Multicluster"
  name: network
spec:
  enabled: true
  extension:
    name: network
    version: 1.0.0
  config: {}
  clusterScheduling:
    placement:
      clusters:
      - host
