apiVersion: v2
appVersion: v4.1.0
dependencies:
- alias: redisHA
  condition: redisHA.enabled
  name: redis-ha
  repository: ""
  version: 4.26.1
description: A Helm chart for KubeSphere Core components
name: ks-core
type: application
version: 1.0.0
