apiVersion: kubesphere.io/v1alpha1
kind: InstallPlan
metadata:
  annotations:
    kubesphere.io/installation-mode: "multi-cluster"
  name: whizard-auditing
spec:
  enabled: true
  extension:
    name: whizard-auditing
    version: 1.0.0
  config: |-
    global:
      imageRegistry: ""
      nodeSelector: {}
      imagePullSecrets: []
      clusterInfo: {}
    
    kube-auditing:
      sinks:
        opensearch:
          # Create opensearch sink or not
          enabled: true
          # Configurations for the opensearch sink, more info for https://vector.dev/docs/reference/configuration/sinks/elasticsearch/
          # Usually users needn't change the following OpenSearch sink config, and the default sinks in secret "kubesphere-logging-system/vector-sinks" created by the WhizardTelemetry Data Pipeline extension will be used.
      #    metadata:
      #      api_version: v8
      #      auth:
      #        strategy: basic
      #        user: admin
      #        password: admin
      #      batch:
      #        timeout_secs: 5
      #      buffer:
      #        max_events: 10000
      #      endpoints:
      #        - https://opensearch-cluster-data.kubesphere-logging-system.svc:9200
      #      tls:
      #        verify_certificate: false
  clusterScheduling:
    placement:
      clusters:
      - host
